apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: credit-dispute-merchant-contact
  labels:
    strimzi.io/cluster: demo-cluster
spec:
  partitions: 50
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
