---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 2a5cc79d61437ad862254b714c19901ada86c0c6
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: credit-dispute-create-service
    provider: fabric8
    version: 1.0.0.0
    group: org.example
  name: credit-dispute-create-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: credit-dispute-create-service
    provider: fabric8
    group: org.example
