spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.1"
              memory: 256Mi
            limits:
              cpu: "0.5"
              memory: 500Mi
          env:
            - name: BOOTSTRAP_SERVERS
              value: "demo-cluster-kafka-bootstrap:9092"
            - name: PRODUCER_TOPIC
              value: credit-dispute-submitted
            - name: SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: SERIALIZER_CLASS
              value: org.example.domain.dispute.serde.DisputeSerializer
            - name: ACKS
              value: 1
